-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id integer,
    email character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_details
(
    user_id integer,
    firstname character varying(50),
    lastname character varying(50)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id integer,
    project_name character varying(50),
    active boolean,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projects_projects
(
    projects_id integer,
    projects_id integer
);

ALTER TABLE IF EXISTS public.user_details
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.projects_projects
    ADD FOREIGN KEY (projects_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.projects_projects
    ADD FOREIGN KEY (projects_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;