-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.department
(
    department_id bigserial NOT NULL,
    department_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    department_city character varying(50),
    CONSTRAINT departments_pkey PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id bigserial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    surname character varying(50) COLLATE pg_catalog."default",
    gender character(1),
    address character varying(50),
    email character varying(30),
    department_id bigserial,
    role_id bigserial,
    salary_id bigserial,
    overtime_id bigserial,
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id bigserial NOT NULL,
    role character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT jobs_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.overtime_hours
(
    overtime_id bigserial NOT NULL,
    overtime_hours integer
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    salary_id bigserial NOT NULL,
    salary_pa numeric(10, 2),
    CONSTRAINT salaries_pkey PRIMARY KEY (salary_id)
);

ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (salary_id)
    REFERENCES public.salaries (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (overtime_id)
    REFERENCES public."overtime hours" (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;


----- INSERT STATEMENTS -----

INSERT INTO department (department_name, department_city)
VALUES 
('Maintanance', 'Pretoria'),
('logistics', 'Kempton park'),
('IT', 'Midrand');
SELECT * FROM department

INSERT INTO roles (role)
VALUES 
('Maintance Manager'),
('Driver'),
('Software programmer');
SELECT * FROM roles

INSERT INTO salaries (salary_pa)
VALUES 
('170000'),
('200000'),
('240000');
SELECT * FROM salaries

INSERT INTO overtime_hours (overtime_hours)
VALUES 
('20'),
('10'),
('80');
SELECT * FROM overtime_hours

INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Wlliams', 'Rathoga', 'M', '175 Steve Biko Pretoria 0002', 'Willy@email.com', 1, 1, 1, 1),
('Ronewa', 'Mudau', 'M', '41 malibongwe DR Jhb 112', 'mudau@email.com', 2, 2, 2, 2),
('Zelda', 'Maluleke', 'F', 'Steve biko Jhb 2620', 'zelda@email.com', 3, 3, 3, 3);
SELECT * FROM employees


UPDATE overtime_hours
SET overtime_hours = 50
WHERE overtime_id = 3


-----LEFT JOIN------

SELECT emp.emp_id, 
emp.first_name, 
emp.surname, 
dept.depart_name, 
roles.role AS job_title,
sal.salary_pa,
ot.overtime_hours
FROM employees AS emp 
LEFT JOIN department AS dept
ON emp.depart_id = dept.depart_id 
LEFT JOIN roles 
ON emp.role_id = roles.role_id
LEFT JOIN salaries AS sal
ON emp.salary_id = sal.salary_id
LEFT JOIN overtime_hours AS ot
ON emp.overtime_id = ot.overtime_id
ORDER BY emp_id 

----TEST CONSTRAINS----

INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Steve', 'Joss', 'M', '24 Meedowlands', 'stevejoss@email.com', 4, 1, 1, 1);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_depart_id_fkey"
-- Detail: Key (depart_id)=(4) is not present in table "department".

INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Musa', 'Khoza', 'M', '22 Mamelodi east', 'musa@email.com', 2, 6, 1, 2);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_role_id_fkey"
-- Detail: Key (role_id)=(5) is not present in table "roles".

INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Elsie', 'Makhado', 'F', '28 Arcadia street', 'elsyy@email.com', 1, 2, 5, 8);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_salary_id_fkey"
-- Detail: Key (salary_id)=(6) is not present in table "salaries".

INSERT INTO employees (first_name, surname, gender, address, email, depart_id, role_id, salary_id, overtime_id)
VALUES 
('Calvin', 'Bassie', 'M', '29 Brooklyn', 'Bassy@email.com', 3, 3, 1, 6);
-- ERROR:  insert or update on table "employees" violates foreign key constraint "employees_overtime_id_fkey"
-- Detail: Key (overtime_id)=(7) is not present in table "overtime_hours