-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.products_menu
(
    prodcuct_id bigserial,
    name character varying(50),
    price numeric(10),
    PRIMARY KEY (prodcuct_id)
);

CREATE TABLE IF NOT EXISTS public.cart
(
    product_id integer,
    qty integer,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigserial,
    username character varying(50),
    PRIMARY KEY (user_Id)
);

CREATE TABLE IF NOT EXISTS public.order_header
(
    order_id bigserial,
    user_id integer,
    orderdate time with time zone,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    order_id integer,
    product_id integer,
    qty integer
);

ALTER TABLE IF EXISTS public.products_menu
    ADD FOREIGN KEY (prodcuct_id)
    REFERENCES public.order_details (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cart
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products_menu (prodcuct_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_header
    ADD FOREIGN KEY (order_id)
    REFERENCES public.users (user_Id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_details
    ADD FOREIGN KEY (order_id)
    REFERENCES public.order_header (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

------------------------INSERT STATEMENTS-------------

INSERT INTO products_menu (name, price)
VALUES 
('Sneaker', '1500.00'),
('Shirt', '400.00'),
('T-shirt', '449.99'),
('Flip-flops', '300.00'), 
('Necklace', '150.00'),
('Smartwatch', '2999.99'),
('Hoodie', '399.99');
SELECT * FROM products_menu;

INSERT INTO users (username)
VALUES 
('Steve'),
('Ronald'),
('Marry'),
('Lettica'),
('Mpho'),
('Vuyani'),
('Bob');
SELECT * FROM users;

-------Queries----

---------CheckOut----


-- USER 
-- adding to cart
DO $$
BEGIN
IF EXISTS ( SELECT * FROM cart WHERE product_id = 5 AND qty > 1) THEN 
UPDATE cart SET qty = qty - 1 WHERE product_id = 4;
ELSE 
DELETE  FROM cart WHERE product_id = 1;
END IF;
END $$
SELECT * FROM cart

SELECT 
cart.product_id,
prod_m.name,
prod_m.price AS unit_price,
cart.qty
FROM cart AS cart
JOIN products_menu AS prod_m
ON cart.product_id = prod_m.product_id;

---deleting from cart
DO $$
BEGIN
IF EXISTS ( SELECT * FROM cart WHERE product_id = 5 AND qty > 1) THEN 
UPDATE cart SET qty = qty - 1 WHERE product_id = 3;
ELSE
 
DELETE  FROM cart WHERE product_id = 2;
END IF;
END $$
SELECT * FROM cart

SELECT 
cart.product_id,
prod_m.name,
prod_m.price,
cart.qty
FROM cart AS cart
JOIN products_menu AS prod_m
ON cart.product_id = prod_m.product_id;

--checkout
INSERT INTO order_header(user_id, order_date)
VALUES 
(2, now());
SELECT * FROM order_header;

SELECT 
od_h.order_id,
od_h.user_id,
users.username,
od_h.order_date
FROM order_header AS od_h JOIN users ON od_h.user_id = users.user_id


INSERT INTO order_details(order_id, product_id, qty)
SELECT
(SELECT MAX(order_id) FROM order_header), product_id, qty 
FROM cart;
DELETE FROM cart;
SELECT * FROM cart

-----Sigle Order----
SELECT 
o_d.order_id,
users.username,
p_m.name AS item,
o_d.qty,
p_m.price AS unit_price,
o_h.order_date
FROM order_details AS o_d JOIN order_header AS o_h ON o_d.order_id = o_h.order_id
JOIN users ON users.user_id = o_h.user_id
JOIN products_menu AS p_m ON p_m.product_id = o_d.product_id
WHERE o_d.order_id = 5;



-- multiple orders---
SELECT 
    od_details.order_id,
    users.username,
    prod_m.name AS item,
    od_details.qty,
    prod_m.price AS unit_price,
    od_h.order_date
FROM order_details AS od_details 
JOIN order_header AS od_h ON od_details.order_id = od_h.order_id
JOIN users ON users.user_id = od_h.user_id
JOIN products_menu AS prod_m ON prod_m.product_id = od_details.product_id;